USE NBAPLAYSDB

CREATE TABLE #TABLE
  (
     WORD  VARCHAR(100) PRIMARY KEY,
     SCORE INT NULL
  )

CREATE TABLE #DESCRIPTIONS
  (
     ROW_ID INT IDENTITY(1, 1) PRIMARY KEY,
     STRING VARCHAR(200)
  )

INSERT INTO #DESCRIPTIONS
            (STRING)
(SELECT DISTINCT HOMEDESCRIPTION
 FROM   PLAY_DATA_SHORT
 WHERE HOMEDESCRIPTION IS NOT NULL)

INSERT INTO #DESCRIPTIONS
            (STRING)
(SELECT DISTINCT VISITORDESCRIPTION
 FROM   PLAY_DATA_SHORT
 WHERE VISITORDESCRIPTION IS NOT NULl)

DECLARE @ROW_NUM INT = (SELECT Count(*) FROM   #DESCRIPTIONS)
DECLARE @COUNTER INT = 1

WHILE @COUNTER <= @ROW_NUM
  BEGIN
      DECLARE @WORDS VARCHAR(MAX) = (SELECT STRING FROM #DESCRIPTIONS WHERE ROW_ID = @COUNTER)

      SELECT VALUE
      INTO   #WORDS
      FROM   STRING_SPLIT(@WORDS, '''')

      INSERT INTO #TABLE
                  (WORD)
      (SELECT VALUE
       FROM   #WORDS W
              LEFT JOIN #TABLE T
                     ON T.WORD = W.VALUE
       WHERE  T.WORD IS NULL)

      DROP TABLE #WORDS

      SET @COUNTER += 1
  END

UPDATE #TABLE
SET    WORD = N.NEW_WORD
FROM   (SELECT WORD + '''' AS NEW_WORD,
               WORD
        FROM   #TABLE
        WHERE  WORD LIKE '[0-9][0-9]'
                OR WORD LIKE '[0-9]'
                OR WORD LIKE 'MISS  [0-9]'
                OR WORD LIKE 'MISS  [0-9][0-9]') AS N
WHERE  N.WORD = #TABLE.WORD

DROP TABLE #DESCRIPTIONS, #TABLE 